services:
  app:
    image: phonebook-frontend
    build:
      context: ./phonebook # The context will pick this directory as the "build context"
      dockerfile: Dockerfile # This will simply tell which dockerfile to read
    container_name: phonebook-frontend # This will name the container phonebook-frontend
    depends_on:
      - app-backend # wait for the backend container to be started
  nginx:
    image: nginx:1.29
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy
    depends_on:
      - app # wait for the frontend container to be started
  app-backend:
    image: phonebook_backend
    build:
      context: ./phonebook_backend # The context will pick this directory as the "build context"
      dockerfile: Dockerfile # This will simply tell which dockerfile to read
    environment:
      - MONGO_URI=mongodb://the_username:the_password@mongo:27017/the_database
    container_name: phonebook_backend # This will name the container phonebook-backend
    depends_on:
      mongo:
        condition: service_started # wait for the mongo container to be started
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - ./phonebook-backend/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - ./mongo_data:/data/db
  